#!/usr/bin/env php
<?php

declare(strict_types=1);

$autoload = __DIR__ . '/vendor/autoload.php';
if (!is_file($autoload)) {
    $autoload = __DIR__ . '/../../autoload.php';
}
if (!is_file($autoload)) {
    fwrite(STDERR, "Laravel Doctor: autoload não encontrado. Execute 'composer install' no projeto.\n");
    exit(1);
}
require_once $autoload;

use LaravelDoctor\Commands\DoctorCommand;
use LaravelDoctor\Config\ConfigLoader;
use LaravelDoctor\Analyzers\AnalyzerRegistry;
use Symfony\Component\Console\Application;

$application = new Application('Laravel Doctor', '0.1');
$application->add(new DoctorCommand(new ConfigLoader(), new AnalyzerRegistry()));
$application->setDefaultCommand('doctor', true);
$application->run();
